import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import Nav from "./components/nav/page";
import Footer from "./components/footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "kuisine229",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="max-sm:mb-14">
          <Nav />
          <div>
            <div className="flex flex-col justify-center items-center">
              <Link
                className="flex items-center justify-center w-full sm:hidden"
                href="/"
              >
                <img
                  className="h-14 w-14"
                  src="/icons/fly_icon.svg"
                  alt="flyapp_logo"
                />
              </Link>

              {children}
            </div>
          </div>
          <footer className="sticky max-sm:hidden sm:mb-8">
            <Footer />
          </footer>
        </main>
      </body>
    </html>
  );
}
